/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

import com.toedter.calendar.JDateChooser;
import conexion.Estudiante;
import conexion.conexionMysql;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import principal.frmlogin;

/**
 *
 * @author pc
 */
public class PANEL_USUARIO extends javax.swing.JFrame {
    DefaultComboBoxModel modelo;
    
    
    /**
     * Creates new form PANEL_USUARIO
     */
    public PANEL_USUARIO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtestados = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtcivil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txttipoidentificacion = new javax.swing.JComboBox<>();
        txtidentificacion = new javax.swing.JTextField();
        txtmodificar = new javax.swing.JButton();
        txtregistro = new javax.swing.JButton();
        txteliminar = new javax.swing.JButton();
        txtlimpiar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JButton();
        txttelefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT REGISTRATION");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro Estudiantil");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado");

        txtestados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Distrito Capital", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia", "12", "1" }));
        txtestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado Civil");

        txtcivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a" }));
        txtcivil.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identificación");

        txttipoidentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cédula Venezolana", "Pasaporte" }));
        txttipoidentificacion.setToolTipText("");

        txtidentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidentificacionActionPerformed(evt);
            }
        });

        txtmodificar.setText("Modificar");
        txtmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodificarActionPerformed(evt);
            }
        });

        txtregistro.setText("Registrar");
        txtregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroActionPerformed(evt);
            }
        });

        txteliminar.setText("Eliminar");
        txteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteliminarActionPerformed(evt);
            }
        });

        txtlimpiar.setText("Limpiar");
        txtlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlimpiarActionPerformed(evt);
            }
        });

        txtbuscar.setText("Buscar");
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtregistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txteliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtlimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcivil, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtestados, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttipoidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttipoidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbuscar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlimpiar)
                    .addComponent(txteliminar)
                    .addComponent(txtmodificar)
                    .addComponent(txtregistro))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidentificacionActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroActionPerformed
        // TODO add your handling code here:
        
        
        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String telefono = txttelefono.getText();
        String estadoNombre = txtestados.getSelectedItem().toString();
        String estadoCivilNombre = txtcivil.getSelectedItem().toString();
        String documentoNombre = txttipoidentificacion.getSelectedItem().toString();
        String identificacion = txtidentificacion.getText();
        
        if (nombre.isEmpty()||apellido.isEmpty()||telefono.isEmpty()||estadoNombre.isEmpty()||estadoCivilNombre.isEmpty()||documentoNombre.isEmpty()||identificacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar los datos");
        } else {
            conexionMysql con = new conexionMysql();
            int respuesta = con.Reusuario(nombre, apellido, telefono, estadoNombre, estadoCivilNombre, documentoNombre, identificacion);
            if (respuesta==1) {
                JOptionPane.showMessageDialog(null, "Estudiante registrado con exito");

            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar estudiante");
            }
        }
        
        
    
    }//GEN-LAST:event_txtregistroActionPerformed

    private void txtestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadosActionPerformed

    private void txtmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodificarActionPerformed
        // TODO add your handling code here:
    // Obtener datos del formulario
    
    String identificacion = txtidentificacion.getText();
    String nombre = txtnombre.getText();
    String apellido = txtapellido.getText();
    String telefono = txttelefono.getText();
    String estadoNombre = txtestados.getSelectedItem().toString();
    String estadoCivilNombre = txtcivil.getSelectedItem().toString();
    String documentoNombre = txttipoidentificacion.getSelectedItem().toString();
        if (nombre.isEmpty()||apellido.isEmpty()||telefono.isEmpty()||estadoNombre.isEmpty()||estadoCivilNombre.isEmpty()||documentoNombre.isEmpty()||identificacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar los datos");
        } else {
            // Crear instancia de la conexión
            conexionMysql con = new conexionMysql();

            // Actualizar estudiante y obtener respuesta
            int respuesta = con.Acestudiante(identificacion, nombre, apellido, telefono, estadoNombre, estadoCivilNombre, documentoNombre);

            // Mostrar mensaje según la respuesta
            if (respuesta == 1) {
                JOptionPane.showMessageDialog(null, "Estudiante actualizado con éxito");
            }
            
        }
    
    }//GEN-LAST:event_txtmodificarActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
        String identificacion = txtidentificacion.getText();
        if (identificacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes completar el campo");
        }

    // Crear instancia de la conexión
        conexionMysql con = new conexionMysql();

        // Buscar estudiante por identificación
        Estudiante estudiante = con.buscarEstudiantePorIdentificacion(identificacion);

        if (estudiante != null) {
            // Rellenar campos con los datos del estudiante
            txtnombre.setText(estudiante.getNombre());
            txtapellido.setText(estudiante.getApellido());
            txttelefono.setText(estudiante.getTelefono());
            txtestados.setSelectedItem(estudiante.getEstado());
            txtcivil.setSelectedItem(estudiante.getEstadoCivil());
            txttipoidentificacion.setSelectedItem(estudiante.getDocumento());
            txtidentificacion.setText(estudiante.getIdentificacion());
        } else {
            JOptionPane.showMessageDialog(null, "Estudiante no encontrado");
        }
    }

    
    private Date parseFecha(String fecha) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            return (Date) sdf.parse(fecha);
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteliminarActionPerformed
        String identificacion = txtidentificacion.getText(); // Obtener la identificación del campo de texto

        if (identificacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una identificación");
            return;
        }

        conexionMysql con = new conexionMysql();
        int respuesta = con.Elusuario(identificacion);

        if (respuesta > 0) {
            JOptionPane.showMessageDialog(null, "Se ha eliminado con éxito");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar");
        }
    }//GEN-LAST:event_txteliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cierra la ventana de registro estudiantil y abre la ventana de login
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlimpiarActionPerformed
        
        // Limpiar campos de texto
        txtidentificacion.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txttelefono.setText("");

        // Restablecer JComboBox a la opción por defecto
        txttipoidentificacion.setSelectedIndex(0);          // Restablecer a la primera opción, generalmente "Seleccionar"
        txtestados.setSelectedIndex(0);    // Hacer lo mismo para otros JComboBox
        txtcivil.setSelectedIndex(0);

        
        // Si tienes más JComboBox, añade las líneas correspondientes para cada uno
        // cmbOtroComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_txtlimpiarActionPerformed
    private void limpiar() {
        // Limpiar campos de texto
        txtidentificacion.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txttelefono.setText("");

        // Restablecer JComboBox a la opción por defecto
        txttipoidentificacion.setSelectedIndex(0);          // Restablecer a la primera opción, generalmente "Seleccionar"
        txtestados.setSelectedIndex(0);    // Hacer lo mismo para otros JComboBox
        txtcivil.setSelectedIndex(0);

        
        // Si tienes más JComboBox, añade las líneas correspondientes para cada uno
        // cmbOtroComboBox.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANEL_USUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANEL_USUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANEL_USUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANEL_USUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANEL_USUARIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JButton txtbuscar;
    private javax.swing.JComboBox<String> txtcivil;
    private javax.swing.JButton txteliminar;
    private javax.swing.JComboBox<String> txtestados;
    private javax.swing.JTextField txtidentificacion;
    private javax.swing.JButton txtlimpiar;
    private javax.swing.JButton txtmodificar;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JButton txtregistro;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JComboBox<String> txttipoidentificacion;
    // End of variables declaration//GEN-END:variables
}
